### ISSUE TITLE
FSP To-Do List

### ISSUE THREAD

**Issue by mwmadsen67** [oli223lopez/AllTreks#1]
# Wiki Page Home

- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the MVP List
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain superfluous routes
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Hey Oliver, great work so far, just a few comments:

**MVP List:** 
- Having a CRUD MVP early on in your list is important. So maybe being able to create your own hike should be an MVP after creating the hike show page. 
- Reviews and driving directions on the hike show is too much for one MVP. Reviews could be its own MVP. Otherwise the formatting is great, should just rethink the MVPs.
- I am wondering how important it is to have national parks as a major MVP.

**Schema:** 
- I would add a locations table or something similarly named, so that you could build a hike from one point to another on a map. The lat and long could be part of the locations rather than the hike, since the hike will have varying lat and long.
- Not sure if you'll need the tabs table. Otherwise, everything else looks good 👍 

**Sample State:** 
- Users slice of state will need some extra associated info, like profPicUrl, hikeIds, photoIds, etc.
- Same thing for other slices of state. Think of has_many relationships.
- Some things will need to be reworked after changing schema.

**Frontend Routes:** These look great but will need to be reworked. Not sure why some of the text is light grey though.

**Backend Routes:** Same as above, formatting is great, makes sense but we'll need to rework a bit.

If you have comments feel free to leave them here, happy to meet as well to talk about changes.
